apiVersion: v1
kind: Service
metadata:
  name: nsqlookupd
  labels:
    app: nsq
  annotations:
    # Enable automatic monitoring of all instances when Prometheus is running in the cluster.
    prometheus.io/scrape: "true"
    prometheus.io/path: "ping"
    prometheus.io/port: "4161"
spec:
  ports:
  - port: 4160
    targetPort: 4160
    name: tcp
  - port: 4161
    targetPort: 4161
    name: http
  clusterIP: None
  selector:
    app: nsq
    component: nsqlookupd
---
apiVersion: v1
kind: Service
metadata:
  name: nsqd
  labels:
    app: nsq
  annotations:
    # Enable automatic monitoring of all instances when Prometheus is running in the cluster.
    prometheus.io/scrape: "true"
    prometheus.io/path: "ping"
    prometheus.io/port: "4151"
spec:
  ports:
  - port: 4150
    targetPort: 4150
    name: tcp
  - port: 4151
    targetPort: 4151
    name: http
  clusterIP: None
  selector:
    app: nsq
    component: nsqd
---
apiVersion: v1
kind: Service
metadata:
  name: nsqadmin
  labels:
    app: nsq
  annotations:
    # Enable automatic monitoring of all instances when Prometheus is running in the cluster.
    prometheus.io/scrape: "true"
    prometheus.io/path: "ping"
    prometheus.io/port: "4171"
spec:
  ports:
  - port: 4170
    targetPort: 4170
    name: tcp
  - port: 4171
    targetPort: 4171
    name: http
  clusterIP: None
  type: LoadBalancer
  selector:
    app: nsq
    component: nsqadmin
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: nsqlookupd
spec:
  serviceName: "nsqlookupd"
  replicas: 3
  template:
    metadata:
      labels:
        app: nsq
        component: nsqlookupd
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
      - name: nsqlookupd
        image: sporkmonger/nsq-k8s:0.3.8
        imagePullPolicy: Always
        ports:
        - containerPort: 4160
          name: tcp
        - containerPort: 4161
          name: http
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 2
        command:
          - /usr/local/bin/nsqlookupd
      # No pre-stop hook is required, a SIGTERM plus some time is all that's
      # needed for graceful shutdown of a node.
      terminationGracePeriodSeconds: 5
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: nsqd
spec:
  serviceName: "nsqd"
  replicas: 4
  template:
    metadata:
      labels:
        app: nsq
        component: nsqd
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
      - name: nsqd
        image: sporkmonger/nsq-k8s:0.3.8
        imagePullPolicy: Always
        ports:
        - containerPort: 4150
          name: tcp
        - containerPort: 4151
          name: http
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 2
        volumeMounts:
        - name: datadir
          mountPath: /data
        command:
          - /usr/local/bin/nsqd
          - -data-path
          - /data
          - -lookupd-tcp-address
          - nsqlookupd-0.nsqlookupd.default.svc.cluster.local:4160
          - -lookupd-tcp-address
          - nsqlookupd-1.nsqlookupd.default.svc.cluster.local:4160
          - -lookupd-tcp-address
          - nsqlookupd-2.nsqlookupd.default.svc.cluster.local:4160
      # No pre-stop hook is required, a SIGTERM plus some time is all that's
      # needed for graceful shutdown of a node.
      terminationGracePeriodSeconds: 5
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: nsqadmin
spec:
  serviceName: "nsqadmin"
  replicas: 1
  template:
    metadata:
      labels:
        app: nsq
        component: nsqadmin
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
      - name: nsqadmin
        image: sporkmonger/nsq-k8s:0.3.8
        imagePullPolicy: Always
        ports:
        - containerPort: 4170
          name: tcp
        - containerPort: 4171
          name: http
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
        command:
          - /usr/local/bin/nsqadmin
          - -lookupd-http-address
          - nsqlookupd-0.nsqlookupd.default.svc.cluster.local:4161
          - -lookupd-http-address
          - nsqlookupd-1.nsqlookupd.default.svc.cluster.local:4161
          - -lookupd-http-address
          - nsqlookupd-2.nsqlookupd.default.svc.cluster.local:4161
      # No pre-stop hook is required, a SIGTERM plus some time is all that's
      # needed for graceful shutdown of a node.
      terminationGracePeriodSeconds: 5
